image: opensuse/leap

build_opensuse:
  stage: build
  image: opensuse/leap
  #only:
  #  - merge_requests
  before_script:
    - zypper refresh
    - zypper --non-interactive update
    # basic
    - zypper --non-interactive install curl ca-certificates cmake git
    - chmod a+x maintainer/ci-build.sh
  script:
    - maintainer/ci-build.sh
