include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml
  #- https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-applications-linux.yml
  #- https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-applications-freebsd.yml
  #- https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-applications-windows.yml

variables:
  PRODUCT: Applications

linux kf5-qt5 qt5.12:
  image: "kdeorg/ci-suse-qt512"
  extends: .linux
  only:
    #- master
    #- merge_requests
  variables:
    PLATFORM: SUSEQt5.12
    BRANCH_GROUP: kf5-qt5

linux stable-kf5-qt5 qt5.12:
  image: "kdeorg/ci-suse-qt512"
  extends: .linux
  only:
    - /^release\/.*$/
  variables:
    PLATFORM: SUSEQt5.12
    BRANCH_GROUP: stable-kf5-qt5

variables:
  PRODUCT: Applications

windows kf5-qt5 qt5.13:
  extends: .windows
  only:
    #- master
    #- merge_requests
  variables:
    CI_PLATFORM: WindowsMSVCQt5.13
    BRANCH_GROUP: kf5-qt5

windows stable-kf5-qt5 qt5.13:
  extends: .windows
  only:
    - /^release\/.*$/
  variables:
    CI_PLATFORM: WindowsMSVCQt5.13
    BRANCH_GROUP: stable-kf5-qt5
