image: debian:stretch-slim

build_ubuntu_18_04:
  stage: build
  image: ubuntu:bionic
  #only:
  #  - merge_requests
  before_script:
    - sed -i -e 's/# deb-src/deb-src/g' /etc/apt/sources.list
    - apt-get update
    # basic
    - apt-get install --yes --no-install-recommends curl ca-certificates
    - chmod a+x maintainer/ci-build.sh
  script:
    - maintainer/ci-build.sh
