image: debian:stretch-slim

build_ubuntu_18_04:
  stage: build
  image: ubuntu:bionic
  #only:
  #  - merge_requests
  before_script:
    - sed -i -e 's/# deb-src/deb-src/g' /etc/apt/sources.list
    - apt-get update
    - apt-get build-dep --yes --no-install-recommends umbrello
    - apt-get install --yes --no-install-recommends ninja-build libkf5crash-dev curl ca-certificates git
  script:
    - sh -x maintainer/ci-build.sh
