image: opensuse/leap

system_check:
  stage: build
  image: opensuse/leap
  variables:
    ci_variant: "check"
  before_script:
  script:
    - maintainer/ci-build.sh

build_local:
  stage: build
  image: opensuse/leap
  #only:
  #  - merge_requests
  variables:
    ci_variant: "local"
  before_script:
    - zypper refresh
    - zypper --non-interactive update
  script:
    - maintainer/ci-build.sh

build:obs:
  stage: build
  when: manual
  image: opensuse/leap
  variables:
    ci_variant: "remote"
  before_script:
    - zypper --non-interactive install curl ca-certificates
  script:
    - maintainer/ci-build.sh
