image: opensuse/leap

system_check:
  stage: build
  when: manual
  image: opensuse/leap
  variables:
    ci_variant: "check"
  before_script:
  script:
    - maintainer/ci-build.sh

build_local_kf5:
  stage: build
  when: manual
  image: opensuse/leap
  #only:
  #  - merge_requests
  variables:
    ci_variant: "local-kf5"
  before_script:
    - zypper modifyrepo --enable repo-source
    - zypper refresh
    - zypper --non-interactive update
  script:
    - maintainer/ci-build.sh

build_local_mingw32:
  stage: build
  when: manual
  image: opensuse/leap
  #only:
  #  - merge_requests
  variables:
    ci_variant: "local-mingw32"
  before_script:
    - zypper modifyrepo --enable repo-source
    - zypper refresh
    - zypper --non-interactive update
  script:
    - maintainer/ci-build.sh

build:obs:
  stage: build
  when: manual
  image: opensuse/leap
  variables:
    ci_variant: "remote"
  before_script:
    - zypper --non-interactive install curl ca-certificates
  script:
    - maintainer/ci-build.sh
